/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 12 "mpi_comm.c"
void __globinit_mpi_comm(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestGetMPIInfo(void)  __attribute__((__crest_skip__)) ;
extern void __CrestWorldSize(unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestRank(unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestBranchOnly(int bid )  __attribute__((__crest_skip__)) ;
#line 211 "/usr/lib/gcc/x86_64-linux-gnu/4.4.7/include/stddef.h"
typedef unsigned long size_t;
#line 131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
#line 139 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __time_t;
#line 75 "/usr/include/time.h"
typedef __time_t time_t;
#line 44 "/usr/include/stdio.h"
struct _IO_FILE;
#line 44
struct _IO_FILE;
#line 48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 144 "/usr/include/libio.h"
struct _IO_FILE;
#line 154 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 160 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 245 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 133 "/usr/include/time.h"
struct tm {
   int tm_sec ;
   int tm_min ;
   int tm_hour ;
   int tm_mday ;
   int tm_mon ;
   int tm_year ;
   int tm_wday ;
   int tm_yday ;
   int tm_isdst ;
   long tm_gmtoff ;
   char const   *tm_zone ;
};
#line 96 "/usr/include/mpich/mpi.h"
typedef int MPI_Datatype;
#line 265 "/usr/include/mpich/mpi.h"
typedef int MPI_Comm;
#line 270 "/usr/include/mpich/mpi.h"
typedef int MPI_Group;
#line 286 "/usr/include/mpich/mpi.h"
typedef int MPI_Op;
#line 466 "/usr/include/stdlib.h"
extern  __attribute__((__nothrow__)) void *malloc(size_t __size )  __attribute__((__malloc__)) ;
#line 169 "/usr/include/stdio.h"
extern struct _IO_FILE *stdout ;
#line 356
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
#line 362
extern int printf(char const   * __restrict  __format  , ...) ;
#line 192 "/usr/include/time.h"
extern  __attribute__((__nothrow__)) time_t time(time_t *__timer ) ;
#line 205
extern  __attribute__((__nothrow__)) size_t strftime(char * __restrict  __s , size_t __maxsize ,
                                                     char const   * __restrict  __format ,
                                                     struct tm  const  * __restrict  __tp ) ;
#line 243
extern  __attribute__((__nothrow__)) struct tm *localtime(time_t const   *__timer ) ;
#line 964 "/usr/include/mpich/mpi.h"
extern int MPI_Reduce(void const   *sendbuf , void *recvbuf , int count , MPI_Datatype datatype ,
                      MPI_Op op , int root , MPI_Comm comm ) ;
#line 983
extern int MPI_Comm_group(MPI_Comm comm , MPI_Group *group ) ;
#line 987
extern int MPI_Group_incl(MPI_Group group , int n , int const   *ranks , MPI_Group *newgroup ) ;
#line 992
extern int MPI_Comm_size(MPI_Comm comm , int *size ) ;
#line 993
extern int MPI_Comm_rank(MPI_Comm comm , int *rank ) ;
#line 997
extern int MPI_Comm_create(MPI_Comm comm , MPI_Group group , MPI_Comm *newcomm ) ;
#line 1041
extern int MPI_Init(int *argc , char ***argv ) ;
#line 1042
extern int MPI_Finalize(void) ;
#line 7 "mpi_comm.c"
int main(int argc , char **argv ) ;
#line 8
void timestamp(void) ;
#line 12 "mpi_comm.c"
int main(int argc , char **argv ) 
{ 
  MPI_Comm even_comm_id ;
  MPI_Group even_group_id ;
  int even_id ;
  int even_id_sum ;
  int even_p ;
  int *even_rank ;
  int i ;
  int id ;
  int ierr ;
  int j ;
  MPI_Comm odd_comm_id ;
  MPI_Group odd_group_id ;
  int odd_id ;
  int odd_id_sum ;
  int odd_p ;
  int *odd_rank ;
  int p ;
  MPI_Group world_group_id ;
  void *tmp ;
  int size1 ;
  void *tmp___0 ;
  int size2 ;
  int *mem_26 ;
  int *mem_27 ;
  int __retres28 ;

  {
  __globinit_mpi_comm();
#line 71
  ierr = MPI_Init(& argc, & argv);
  __CrestGetMPIInfo();
  __CrestWorldSize((unsigned long )(& p));
#line 75
  ierr = MPI_Comm_size(1140850688, & p);
  __CrestRank((unsigned long )(& id));
#line 79
  ierr = MPI_Comm_rank(1140850688, & id);
#line 83
  if (id == 0) {
    __CrestBranchOnly(3);
#line 85
    timestamp();
#line 86
    printf((char const   * __restrict  )"\n");
#line 87
    printf((char const   * __restrict  )"COMMUNICATOR_MPI - Master process:\n");
#line 88
    printf((char const   * __restrict  )"  C/MPI version\n");
#line 89
    printf((char const   * __restrict  )"  An MPI example program.\n");
#line 90
    printf((char const   * __restrict  )"\n");
#line 91
    printf((char const   * __restrict  )"  The number of processes is %d.\n", p);
#line 92
    printf((char const   * __restrict  )"\n");
  } else {
    __CrestBranchOnly(4);

  }
#line 97
  printf((char const   * __restrict  )"  Process %d says \'Hello, world!\'\n", id);
#line 101
  MPI_Comm_group(1140850688, & world_group_id);
#line 105
  even_p = (p + 1) / 2;
#line 106
  tmp = malloc((unsigned long )even_p * sizeof(int ));
#line 106
  even_rank = (int *)tmp;
#line 107
  j = 0;
#line 108
  i = 0;
#line 108
  while (1) {
    while_continue: /* CIL Label */ ;
#line 108
    if (i < p) {
      __CrestBranchOnly(10);

    } else {
      __CrestBranchOnly(11);
#line 108
      goto while_break;
    }
#line 110
    mem_26 = even_rank + j;
#line 110
    *mem_26 = i;
#line 111
    j ++;
#line 108
    i += 2;
  }
  while_break: /* CIL Label */ 
#line 113
  MPI_Group_incl(world_group_id, even_p, (int const   *)even_rank, & even_group_id);
#line 115
  MPI_Comm_create(1140850688, even_group_id, & even_comm_id);
#line 117
  MPI_Comm_size(even_comm_id, & size1);
#line 121
  odd_p = p / 2;
#line 122
  tmp___0 = malloc((unsigned long )odd_p * sizeof(int ));
#line 122
  odd_rank = (int *)tmp___0;
#line 123
  j = 0;
#line 124
  i = 1;
#line 124
  while (1) {
    while_continue___0: /* CIL Label */ ;
#line 124
    if (i < p) {
      __CrestBranchOnly(19);

    } else {
      __CrestBranchOnly(20);
#line 124
      goto while_break___0;
    }
#line 126
    mem_27 = odd_rank + j;
#line 126
    *mem_27 = i;
#line 127
    j ++;
#line 124
    i += 2;
  }
  while_break___0: /* CIL Label */ 
#line 129
  MPI_Group_incl(world_group_id, odd_p, (int const   *)odd_rank, & odd_group_id);
#line 131
  MPI_Comm_create(1140850688, odd_group_id, & odd_comm_id);
#line 133
  MPI_Comm_size(even_comm_id, & size2);
#line 138
  if (id % 2 == 0) {
    __CrestBranchOnly(25);
#line 140
    ierr = MPI_Comm_rank(even_comm_id, & even_id);
#line 141
    odd_id = -1;
  } else {
    __CrestBranchOnly(26);
#line 145
    ierr = MPI_Comm_rank(odd_comm_id, & odd_id);
#line 146
    even_id = -1;
  }
#line 152
  if (even_id != -1) {
    __CrestBranchOnly(28);
#line 154
    MPI_Reduce((void const   *)(& id), (void *)(& even_id_sum), 1, 1275069445, 1476395011,
               0, even_comm_id);
  } else {
    __CrestBranchOnly(29);

  }
#line 156
  if (even_id == 0) {
    __CrestBranchOnly(31);
#line 158
    printf((char const   * __restrict  )"  Number of processes in even communicator = %d\n",
           even_p);
#line 159
    printf((char const   * __restrict  )"  Sum of global ID\'s in even communicator  = %d\n",
           even_id_sum);
  } else {
    __CrestBranchOnly(32);

  }
#line 165
  if (odd_id != -1) {
    __CrestBranchOnly(34);
#line 167
    MPI_Reduce((void const   *)(& id), (void *)(& odd_id_sum), 1, 1275069445, 1476395011,
               0, odd_comm_id);
  } else {
    __CrestBranchOnly(35);

  }
#line 169
  if (odd_id == 0) {
    __CrestBranchOnly(37);
#line 171
    printf((char const   * __restrict  )"  Number of processes in odd communicator  = %d\n",
           odd_p);
#line 172
    printf((char const   * __restrict  )"  Sum of global ID\'s in odd communicator   = %d\n",
           odd_id_sum);
  } else {
    __CrestBranchOnly(38);

  }
#line 177
  ierr = MPI_Finalize();
#line 181
  if (id == 0) {
    __CrestBranchOnly(41);
#line 183
    printf((char const   * __restrict  )"\n");
#line 184
    printf((char const   * __restrict  )"COMMUNICATOR_MPI:\n");
#line 185
    printf((char const   * __restrict  )"  Normal end of execution.\n");
#line 186
    printf((char const   * __restrict  )"\n");
#line 187
    timestamp();
  } else {
    __CrestBranchOnly(42);

  }
#line 189
  __retres28 = 0;
#line 12
  return (__retres28);
}
}
#line 224 "mpi_comm.c"
static char time_buffer[40]  ;
#line 193 "mpi_comm.c"
void timestamp(void) 
{ 
  struct tm  const  *tm ;
  size_t len ;
  time_t now ;
  struct tm *tmp ;

  {
#line 229
  now = time((time_t *)((void *)0));
#line 230
  tmp = localtime((time_t const   *)(& now));
#line 230
  tm = (struct tm  const  *)tmp;
#line 232
  len = strftime((char * __restrict  )(time_buffer), (size_t )40, (char const   * __restrict  )"%d %B %Y %I:%M:%S %p",
                 (struct tm  const  * __restrict  )tm);
#line 234
  fprintf((FILE * __restrict  )stdout, (char const   * __restrict  )"%s\n", time_buffer);

#line 193
  return;
}
}
void __globinit_mpi_comm(void) 
{ 


  {
  __CrestInit();
}
}
