/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

#line 5 "hello.c"
void __globinit_hello(void) ;
extern void __CrestInit(void)  __attribute__((__crest_skip__)) ;
extern void __CrestGetMPIInfo(void)  __attribute__((__crest_skip__)) ;
extern void __CrestWorldSizeWithLimit(unsigned long addr , int limit )  __attribute__((__crest_skip__)) ;
extern void __CrestRankNonDefaultComm2(long long val , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestRankNonDefaultComm1(unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestRank(unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestHandleReturn(int id , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestReturn(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestCall(int id , unsigned int fid )  __attribute__((__crest_skip__)) ;
extern void __CrestBranch(int id , int bid , unsigned char b )  __attribute__((__crest_skip__)) ;
extern void __CrestApply2(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestApply1(int id , int op , long long val )  __attribute__((__crest_skip__)) ;
extern void __CrestClearStack(int id )  __attribute__((__crest_skip__)) ;
extern void __CrestStore(int id , unsigned long addr )  __attribute__((__crest_skip__)) ;
extern void __CrestLoad(int id , unsigned long addr , long long val )  __attribute__((__crest_skip__)) ;
#line 265 "/usr/include/mpich/mpi.h"
typedef int MPI_Comm;
#line 212 "/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h"
typedef unsigned long size_t;
#line 131 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
#line 132 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
#line 44 "/usr/include/stdio.h"
struct _IO_FILE;
#line 44
struct _IO_FILE;
#line 48 "/usr/include/stdio.h"
typedef struct _IO_FILE FILE;
#line 144 "/usr/include/libio.h"
struct _IO_FILE;
#line 154 "/usr/include/libio.h"
typedef void _IO_lock_t;
#line 160 "/usr/include/libio.h"
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
#line 245 "/usr/include/libio.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
#line 992 "/usr/include/mpich/mpi.h"
extern int MPI_Comm_size(MPI_Comm comm , int *size ) ;
#line 993
extern int MPI_Comm_rank(MPI_Comm comm , int *rank ) ;
#line 1030
extern int MPI_Get_processor_name(char *name , int *resultlen ) ;
#line 1041
extern int MPI_Init(int *argc , char ***argv ) ;
#line 1042
extern int MPI_Finalize(void) ;
#line 169 "/usr/include/stdio.h"
extern struct _IO_FILE *stdout ;
#line 242
extern int fflush(FILE *__stream ) ;
#line 362
extern int printf(char const   * __restrict  __format  , ...) ;
#line 226 "/home/westwind/myInstall/Develop/crest.mpi/bin/../include/crest.h"
extern void __CrestIntWithLimit(int *x , long long limit )  __attribute__((__crest_skip__)) ;
#line 5 "hello.c"
int main(int argc , char **argv ) 
{ 
  int world_rank ;
  int a ;
  int world_size ;
  int b ;
  char processor_name[128] ;
  int name_len ;
  int __retres9 ;

  {
  __globinit_hello();
  __CrestCall(2, 1);
  __CrestStore(1, (unsigned long )(& argc));
#line 12
  MPI_Init((int *)((void *)0), (char ***)((void *)0));
  __CrestGetMPIInfo();
#line 14
  __CrestIntWithLimit(& a, 100LL);
  __CrestLoad(5, (unsigned long )(& a), (long long )a);
  __CrestLoad(4, (unsigned long )0, (long long )1);
  __CrestApply2(3, 0, (long long )(a + 1));
  __CrestStore(6, (unsigned long )(& b));
#line 16
  b = a + 1;
  __CrestLoad(9, (unsigned long )(& a), (long long )a);
  __CrestLoad(8, (unsigned long )0, (long long )1);
  __CrestApply2(7, 0, (long long )(a + 1));
  __CrestStore(10, (unsigned long )(& a));
#line 17
  a ++;
  __CrestLoad(11, (unsigned long )0, (long long )1140850688);
  __CrestWorldSizeWithLimit((unsigned long )(& world_size), 16);
#line 25
  MPI_Comm_size(1140850688, & world_size);
  __CrestClearStack(12);
  __CrestLoad(13, (unsigned long )0, (long long )1140850688);
  __CrestRank((unsigned long )(& world_rank));
#line 26
  MPI_Comm_rank(1140850688, & world_rank);
  __CrestClearStack(14);
#line 31
  MPI_Get_processor_name(processor_name, & name_len);
  __CrestClearStack(15);
  __CrestLoad(16, (unsigned long )(& world_rank), (long long )world_rank);
  __CrestLoad(17, (unsigned long )(& world_size), (long long )world_size);
#line 34
  printf((char const   * __restrict  )"Hello world from processor %s, rank %d out of %d processors\n",
         processor_name, world_rank, world_size);
  __CrestClearStack(18);
  __CrestLoad(21, (unsigned long )0, (long long )1);
  __CrestLoad(20, (unsigned long )(& world_size), (long long )world_size);
  __CrestApply2(19, 12, (long long )(1 == world_size));
#line 39
  if (1 == world_size) {
    __CrestBranch(22, 3, 1);
    __CrestLoad(24, (unsigned long )(& world_size), (long long )world_size);
#line 39
    printf((char const   * __restrict  )"world size: %d\n", world_size);
    __CrestClearStack(25);
  } else {
    __CrestBranch(23, 4, 0);
    __CrestLoad(26, (unsigned long )(& world_size), (long long )world_size);
#line 40
    printf((char const   * __restrict  )"world size: %d\n", world_size);
    __CrestClearStack(27);
  }
  __CrestLoad(30, (unsigned long )0, (long long )1);
  __CrestLoad(29, (unsigned long )(& world_rank), (long long )world_rank);
  __CrestApply2(28, 16, (long long )(1 < world_rank));
#line 43
  if (1 < world_rank) {
    __CrestBranch(31, 6, 1);
#line 43
    printf((char const   * __restrict  )"a1:s\n");
    __CrestClearStack(33);
  } else {
    __CrestBranch(32, 7, 0);
#line 44
    printf((char const   * __restrict  )"a2:s\n");
    __CrestClearStack(34);
  }
  __CrestLoad(39, (unsigned long )0, (long long )2);
  __CrestLoad(38, (unsigned long )0, (long long )2);
  __CrestLoad(37, (unsigned long )(& a), (long long )a);
  __CrestApply2(36, 2, (long long )(2 * a));
  __CrestApply2(35, 12, (long long )(2 == 2 * a));
#line 46
  if (2 == 2 * a) {
    __CrestBranch(40, 9, 1);
#line 46
    printf((char const   * __restrict  )"b1:s\n");
    __CrestClearStack(42);
  } else {
    __CrestBranch(41, 10, 0);
#line 47
    printf((char const   * __restrict  )"b2:s\n");
    __CrestClearStack(43);
  }
#line 49
  fflush(stdout);
  __CrestClearStack(44);
#line 51
  MPI_Finalize();
  __CrestClearStack(45);
  __CrestLoad(46, (unsigned long )0, (long long )0);
  __CrestStore(47, (unsigned long )(& __retres9));
#line 52
  __retres9 = 0;
  __CrestLoad(48, (unsigned long )(& __retres9), (long long )__retres9);
  __CrestReturn(49);
#line 5
  return (__retres9);
}
}
void __globinit_hello(void) 
{ 


  {
  __CrestInit();
}
}
